### ISSUE TITLE
Text generation web UI returns "error string extraction: [WinError 1225] The remote computer refused the network connection"

### ISSUE THREAD

**Issue by Athnex** [PsychoSmiley/LLM_Buttplug#2]
Hello.

After installing and setting up everything as described in the README every use of the "stroke(" keyword returns this error:
`Intensity extracted from stroke( 0.5 ):: run_command: 1000, 0.5, True` 
`error string extraction: [WinError 1225] The remote computer refused the network connection` 

 Intiface Central also logs and error:
`Got invalid message from remote Buttplug connection - Message: Text("{\"duration\":1000,\"intensity\":0.8,\"oscillation\":true,\rotation_clockwise\":null}") - Error: JsonSerializedError("Error during JSON Schema Validation . Message: {\"duration\":1000,\"intensity\":0.8,\"oscillation\":true,\"rotation_clockwise\":null} - Error: [ValidationError { instance: Object {\"duration\": Number(1000),\"intensity\": Number(0.8),\"oscillation\": Bool(true),\"rotation_clockwise\": Null}, kind: AnyOf, instance:path: JSONPointer([]), schema_path: JSONPointer([Keyword(\"anyOf\")])}]")`

Tested with Intiface running and connected. Up to the point where the AI uses the "stroke(" keyword, everything works. Tested with Lovense Gush connected and working. I appreciate every help to fix this.

**Comment by PsychoSmiley** [comment]
I suggest first test with same character template and model `Athnete-13B`, error `The remote computer refused the network connection` sometimes happen when not waiting 10 sec at start for scan.

The log: `Intensity extracted from stroke( 0.5 ):: run_command: 1000, 0.5, True` look correct, however if you want to test running server side only you can activate the environment `cmd_{your os}` and execute command at the same file location: https://github.com/PsychoSmiley/LLM_Buttplug/blob/13692372c4ac0e04035cedc06107403a6e267002/templates/example_client.py#L13

If working correctly than `error string extraction` **is most likely bad json message output by the model**. I do not expect keyword `stroke(`x`)` to be string alone, while it can work, json format is helpful to guide model unlikely to make any misstake in long term conversation, unfortunately i cannot reproduce exact same error.

**Comment by Athnex** [comment]
Ok thanks. 

I tried the example client command you suggested (Intiface running; Toy connected; Text generation web UI NOT running). I ran the exact command you specified and got the following error:
The first line is the command I issued, for the sake of completeness.
```
(E:\AI\LLM\text-generation-webui\installer_files\env) E:\AI\LLM\text-generation-webui\extensions\LLM_Buttplug\templates>python example_client.py 100 0.5 True
Traceback (most recent call last):
  File "E:\AI\LLM\text-generation-webui\extensions\LLM_Buttplug\templates\example_client.py", line 23, in <module>
    loop.run_until_complete(send_command(args.duration, args.intensity, args.oscillation))
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\asyncio\base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "E:\AI\LLM\text-generation-webui\extensions\LLM_Buttplug\templates\example_client.py", line 10, in send_command
    async with websockets.connect('ws://127.0.0.1:8769') as websocket:
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\site-packages\websockets\legacy\client.py", line 637, in __aenter__
    return await self
           ^^^^^^^^^^
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\site-packages\websockets\legacy\client.py", line 655, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\site-packages\websockets\legacy\client.py", line 659, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\asyncio\base_events.py", line 1085, in create_connection
    raise exceptions[0]
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\asyncio\base_events.py", line 1069, in create_connection
    sock = await self._connect_sock(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\asyncio\base_events.py", line 973, in _connect_sock
    await self.sock_connect(sock, address)
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\asyncio\windows_events.py", line 846, in _poll
    value = callback(transferred, key, ov)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\AI\LLM\text-generation-webui\installer_files\env\Lib\asyncio\windows_events.py", line 633, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection
```

Is it in any way possible in your opinion that this is caused due to the fact the all the files and packages are not located on my OS Drive? I once had a problem with a different application that threw an error at me simply because it was not installed on C:.

**Comment by PsychoSmiley** [comment]
When i say "server side only", both the extension `LLM_Buttplug text-generation-webui` and `intiface` running.
This extension run separately server`stroke.py` on its own to communicate with `intiface`, this way main `script.py` does not _wait_ in the process.
https://github.com/PsychoSmiley/LLM_Buttplug/blob/13692372c4ac0e04035cedc06107403a6e267002/script.py#L61-L65

**Comment by Athnex** [comment]
Ok thanks for the answer. I misunderstood your first message, sorry.
It seems I fixed the Error. The whole problem seemed to be caused by a Setting inside `IntiFace` that enabled raw messages. As soon as I disabled that everything worked. Thanks for the help nonetheless.
