### ISSUE TITLE
Not an issue but a request would be awesome if it can communicate to an Arduino or Raspberry PI and use external sensors which can include any kind of plugs.

### ISSUE THREAD

**Issue by CRCODE22** [PsychoSmiley/LLM_Buttplug#3]
I love the idea of llm being able to communicate with the physical world. I and many others would love to llm being able to communicate with Arduino or Raspberry PI and by doing so giving them access to all kinds of sensors people can hook up to an Arduino or Raspberry PI. I know these capabilities will come to llm soon would be awesome if you could be the first to achieve this since you already made the butt plug extension :)

**Comment by CRCODE22** [comment]
Good starting points would be here:

https://github.com/delta-G/ArduGPT
https://forum.arduino.cc/t/chatgpt-for-human-input-processing/1126367

**Comment by PsychoSmiley** [comment]
> Arduino or Raspberry PI

Maybe use [Ooba API](https://github.com/oobabooga/text-generation-webui/wiki/12-%E2%80%90-OpenAI-API#chat-completions-with-characters) along with modifying my [character template](https://gist.github.com/PsychoSmiley/9a54b5fdd934435f01ae5146fe516d89)[.](https://github.com/acon96/home-llm)
Don’t want to make any promises as it’s out of AI hobby motivation scope. lol
I don’t have either of them and I want to focus on local development.
