### ISSUE TITLE
Error in interface central

### ISSUE THREAD

**Issue by dBtelm** [PsychoSmiley/LLM_Buttplug#4]
i keep getting this error: 
Got invalid messages from remote Buttplug connection - Message: Text("{\"duration\": 1000,
\"intensity\": 0.1, \"oscillation\": true, \"rotation_clockwise\": null}") - Error:
JsonSerializerError("Error during JSON Schema Validation - Message:
{\"duration\":1000,\"intensity\":0.1,\"oscillation\":true,\"rotation_clockwise\":null} - Error:
[ValidationError { instance: Object {\"duration\": Number(1000), \"intensity\": Number(0.1),
\"oscillation\": Bool(true), \"rotation_clockwise\": Null}, kind: AnyOf, instance_path:
JsonPointer([]), schema_path: JsonPointer([Property(\"anyOf\")]) }]")

is this related to be not having a device connected with stroking?
i only have vibration toys.

**Comment by PsychoSmiley** [comment]
Vibration toys supported and _were_ tested. Seem to be duplicated issue #2 related to `IntiFace` **app** settings..
